version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dialer
      POSTGRES_PASSWORD: strongpass
      POSTGRES_DB: dialer
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dialer -d dialer"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  backend:
    build: ./backend
    env_file: ./.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - recordings:/var/recordings

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    env_file: ./.env
    depends_on:
      - backend
    ports:
      - "3000:3000"

  # FreeSWITCH puede ser externo; este contenedor es opcional para lab.
  freeswitch:
    image: signalwire/freeswitch
    container_name: freeswitch
    network_mode: service:backend # (o ponte en la misma red)
    environment:
      - SOUND_PREFIX=/usr/share/freeswitch/sounds/en/us/callie
    volumes:
      - ./freeswitch/conf:/etc/freeswitch
      - recordings:/var/recordings

  # Nginx como reverse-proxy TLS (puedes usar Caddy/Traefik si prefieres)
  nginx:
    image: nginx:1.27
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ops/nginx/certs:/etc/nginx/certs:ro

volumes:
  pgdata:
  redisdata:
  recordings:
