# k8s/01-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: dialer
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "CAMBIA_ESTE_SECRETO_LARGO"
  JWT_REFRESH_SECRET: "CAMBIA_ESTE_OTRO_SECRETO"
  DATABASE_URL: "postgresql://dialer:strongpass@postgres:5432/dialer"
  REDIS_URL: "redis://redis:6379"
  ESL_HOST: "freeswitch"
  ESL_PORT: "8021"
  ESL_PASSWORD: "ClueCon"
  REC_DIR: "/var/recordings"
  S3_REGION: "us-east-1"
  S3_BUCKET_RECORDINGS: "tubucket-grabaciones"
  CORS_ORIGIN: "https://app.tudominio.com"
  JWT_ACCESS_TTL: "600"
  JWT_REFRESH_TTL_DAYS: "7"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
  namespace: dialer
data:
  NEXT_PUBLIC_API: "https://api.tudominio.com"
  NEXT_PUBLIC_WS: "wss://api.tudominio.com/ws"
