apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dialer-backend
  labels:
    release: prometheus   # ajusta al label de tu kube-prometheus-stack
spec:
  selector:
    matchLabels: { app: dialer-backend }
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
      scrapeTimeout: 10s
